syntax = "proto3";

option csharp_namespace = "Challenge.Common.Messaging.Grpc";

package rider;

service RiderService {
  rpc ValidateRiderCnhType (ValidateRiderRequest) returns (ValidateRiderResponse);
  
  rpc GetRider (GetRiderRequest) returns (GetRiderResponse);
}

message ValidateRiderRequest {
  string rider_identifier = 1;
}

message ValidateRiderResponse {
  bool is_valid = 1;
  string cnh_type = 2;
  string message = 3;
}

message GetRiderRequest {
  string rider_identifier = 1;
}

message GetRiderResponse {
  string identifier = 1;
  string name = 2;
  string cnpj = 3;
  string cnh_number = 4;
  string cnh_type = 5;
  bool active = 6;
}